# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-13 02:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='conten',
            new_name='content',
        ),
    ]
